<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '[полный текст]' => '[full text]',
  'Адрес для ответа' => 'Feed back adress',
  'Выгоды' => 'Benefits',
  'гарантированное<br>качество' => 'quality guarantee',
  'наши клиенты' => 'our clients',
  'новости компании' => 'company news',
  'о компании' => 'about company',
  'предоставляемые<br>услуги' => 'rendering services',
  'Молодая команда высокопрофессиональных специалистов.' => 'The young company with experienced professionals. ',
  'Результат профессиональной уборки - сияние идеальной чистоты..' => 'The result of professional cleaning is ideal shiny cleanliness. ',
  'Качество, которое уже оценили многие компании.' => 'Our quality is appreciated by many companies. ',
  'Мы предоставляем нашим заказчикам реальные выгоды.' => 'We offer very real benefits to you.',
  'Наши партнеры - международные компании с известной репутацией.' => 'Our partners are worldwide known companies which value their reputations ',
  'Обратившись к нам, вы делаете первый шаг к чистоте.' => 'Your first step to cleanliness is to contact us ',
  'КОМПАНИЯ' => 'COMPANY',
  'УСЛУГИ' => 'SERVICES',
  'КАЧЕСТВО' => 'QUALITY',
  'НОВОСТИ' => 'NEWS',
  'КЛИЕНТЫ' => 'CLIENTS',
  'КОНТАКТЫ' => 'CONTACTS',
  'Качество' => 'Quality',
  'Выгоды' => 'Benefits',
);
