<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    '[полный текст]' => '[totul text]',
    'Адрес для ответа' => 'Adresa pentru raspuns',
    'Выгоды' => 'Beneficii',
    'гарантированное<br>качество' => 'garantia calitatii',
    'наши клиенты' => 'garantia calitatii',
    'новости компании' => 'evenimente companiei',
    'о компании' => 'despre companie',
    'предоставляемые<br>услуги' => 'serviciile prestate',
    'Молодая команда высокопрофессиональных специалистов.' => 'O echipă tînără dar cu specialişti profesionişti.',
    'Результат профессиональной уборки - сияние идеальной чистоты..' => 'Rezultatul curăţeniei profesioniste sunt suprafeţele sclipitoare.',
    'Качество, которое уже оценили многие компании.' => 'Calitatea care a fost apreciată deja de multe companii.',
    'Мы предоставляем нашим заказчикам реальные выгоды.' => 'Noi oferim clienţilor noştri beneficii reale.',
    'Наши партнеры - международные компании с известной репутацией.' => 'Partenerii noştri sunt companiile cu renume internaţional.',
    'Обратившись к нам, вы делаете первый шаг к чистоте.' => 'Apelîndu-ne, faceţi primul pas spre curăţenie.',
    'КОМПАНИЯ' => 'COMPANIA',
    'УСЛУГИ' => 'SERVICII',
    'КАЧЕСТВО' => 'CALITATE',
    'НОВОСТИ' => 'EVENIMENTE',
    'КЛИЕНТЫ' => 'CLIENTI',
    'КОНТАКТЫ' => 'CONTACTE',
    'Качество' => 'Calitate',
    'Выгоды' => 'Beneficii',
);
